name: HNGX fastAPI workflow

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up python

        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest
      
      - name: Start FastAPI server
        run: uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 3
      
      - name: Stop Server
        run: pkill -f "uvicorn"